CREATE TABLE IF NOT EXISTS USER_GYM (
    USER_ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255),
    SURNAME VARCHAR(255),
    CODE VARCHAR(16),
    BIRTHDAY DATE,
    PHONE VARCHAR(10),
    EMAIL VARCHAR(255),
    CERTIFICATE VARCHAR(255),
    VALID_DATE DATE,
    SUBSCRIPTION VARCHAR(255),
    SUBSCRIPTION_DATE DATE,
    PRIMARY KEY (USER_ID)
);

CREATE TABLE IF NOT EXISTS ROOM (
    ROOM_ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255),
    PRIMARY KEY (ROOM_ID)
);

CREATE TABLE IF NOT EXISTS COURSE (
    COURSE_ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255),
    ROOM_ID BIGINT NOT NULL,
    PRIMARY KEY (COURSE_ID),
    CONSTRAINT FK_COURSE_ROOM FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ROOM_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TRAINER (
    TRAINER_ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255),
    SURNAME VARCHAR(255),
    EMAIL VARCHAR(255),
    PRIMARY KEY (TRAINER_ID)
);

CREATE TABLE IF NOT EXISTS USER_COURSE (
    USER_ID BIGINT NOT NULL,
    COURSE_ID BIGINT NOT NULL,
    PRIMARY KEY (USER_ID, COURSE_ID),
    CONSTRAINT FK_USER_COURSE_USER FOREIGN KEY (USER_ID) REFERENCES USER_GYM(USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_USER_COURSE_COURSE FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TRAINER_COURSE (
    TRAINER_ID BIGINT NOT NULL,
    COURSE_ID BIGINT NOT NULL,
    PRIMARY KEY (TRAINER_ID, COURSE_ID),
    CONSTRAINT FK_TRAINER_COURSE_TRAINER FOREIGN KEY (TRAINER_ID) REFERENCES TRAINER(TRAINER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_TRAINER_COURSE_COURSE FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID) ON DELETE CASCADE
);